### ISSUE TITLE
Custom data

### ISSUE THREAD

**Issue by samr66** [luferrer/DCA-PLDA#7]
Hi, I want to train and evaluate the model on custom data. Can you explain the structure of the eval files from the example data, I am not 100% sure what needs to be the content of .lst files. enroll.lst and test.lst are identical in the provided example.

**Comment by luferrer** [comment]
The format for both of those files consists of two columns. The first column needs to contain the id of the enrollment or test set, the second column contains the id of one of the embeddings corresponding to that enrollment/test id. For testing one usually has a one-to-one mapping from test id to embedding id. For enrollment, though, one might use N embeddings for a single enrollment id. In that case, the enroll.lst would be as follows:

enroll_id1 embedding1
enroll_id1 embedding2
enroll_id1 embedding3
enroll_id2 embedding4
enroll_id2 embedding5
...

The code will then compute scores for all enrollment vs all test ids (the full matrix). You also need to provide a key file indicating which of those pairs of enrollment and test ids you actually want to consider to compute the performance, along with their label.

I hope that helped. Otherwise, let me know.

**Comment by samr66** [comment]
Thank you for the answer!
The only thing that confuses me is that in .h5 key there is 'train_ids' dataset. Should I put there enrollment ids?

**Comment by luferrer** [comment]
Ah, yes, sorry about that. That should be enroll_ids. Some of my keys still say train_ids (an old nomenclature I inherited from elsewhere) even though the key class now also accepts enroll_ids (see line 41 in scores.py). So you can name the field either way, but they should be the enrollment ids in enroll.lst.
